# Abstract {.unnumbered #ind}


```{r}
#| echo: false
#| eval: true
#| warning: false
#| labl: "loading-packages"

library("ggplot2")
library("dplyr")

library("rjd3toolkit")
library("rjd3x13")
library("rjd3providers")
library("rjd3workspace")
library("rjd3production")
```

## Abstract

Seasonal adjustment is a key process in all public statistical organizations, as it is necessary for the dissemination and interpretation of a large number of economic indicators. In an effort to harmonize practices, Eurostat has recommended since 2015 the use of the open source software JDemetra+, which provides access to the two most popular seasonal adjustment algorithms in European public statistics: X-13 Arima and Tramo-Seats, via a graphical user interface and a family of R packages. This article aims to describe and illustrate how to take advantage of version 3.x of JDemetra+ to build efficient production processes that can adjust several thousand series with individualized settings, while controlling statistical quality and targeting manual fine-tuning.

Keywords: Seasonal adjustment, official statistics, production process, X13-Arima, Tramo-Seats

JEL Classification: C01, C02, C14, C22, C82, C87
