# Introduction {.unnumbered #intro}

Seasonal adjustment is a key process in official statistics. The dissemination of most economic indicators requires that they first be purged of quasi-periodic, seasonal, and calendar movements in order to facilitate the interpretation of short-term developments and the identification of turning points and medium- and long-term trends [@bell1984issues]. However, implementing a standardized and flexible process for producing seasonally and calendar adjusted (sa) series that complies with European statistical system best practices [@eurostat2024guidelines] is costly. <!-- % challenges, implementation difficulties  --> <!-- % good properties of a process --> In addition to producing seasonally adjusted series, it must also provide integrated quality indicators [@ch22HBSA] and allow for manual adjustment by experts, often under significant time constraints. <!-- %good properties of a process  --> <!-- %current situation at INSEE: around JD+ --> At INSEE, all seasonal adjustment processes are built around JDemetra+ [@JD_doc], officially recommended by Eurostat since 2015. This is open source software for time series analysis, providing access to the two most popular seasonal adjustment algorithms in European official statistics: X-13 Arima [@census] and Tramo-Seats [@gomez1996programs]. The algorithms are written in Java and accessible via a [graphical user interface](https://github.com/jdemetra) and a family of R packages: the [rjdverse](https://github.com/rjdverse).

Version 3 of JDemetra+, gradually available since 2023, offers new R tools to optimize production and improve existing processes <!-- % need for mass parameterization --> <!-- %highlighting difficulties  --> In addition, the Covid crisis has highlighted the need for fine-grained parameterization on a very large scale, such as assigning specific outlier profiles to each series for several hundred series. <!-- % transition from SAS to R --> Finally, the emphasis in recent years on the transition from SAS to R at INSEE is promoting the acceptance of these new tools in a general context of modernization. Therefore, the current context is very favorable for reviewing and optimizing existing processes.

Each year, INSEE's Statistical Methods Department undertakes a number of process redesigns, disseminates best practices, and trains producers in the use of the JDemetra+ software. However, in order to clarify the construction and optimization of seasonality adjustment processes, an example of a method and a presentation of the latest tools are necessary.

Currently, producers of seasonally adjusted series have access to theoretical information on seasonal adjustment algorithms, such as the [Handbook on Seasonal Adjustment](https://ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/ks-gq%20-18-001), a guide to [best practices](https://ec.europa.eu/eurostat/web/products-manuals-and-guidelines/w/ks-gq%20-24-012), the [JDemetra+ software documentation](https://jdemetra-new-documentation.netlify.app/), and possibly notes reflecting the historical sedimentation of practices in your institution. One piece seems to be missing from this puzzle: a specific example of implementation using the most up-to-date tools. The rest of this article aims to describe and illustrate how to take advantage of JDemetra+ version 3.x to build efficient production processes, adjust up to several thousand series with individualized settings, control statistical quality, and target manual fine-tuning.

The production of seasonally adjusted series generally involves three stages: the process of installation, during which methodological changes are most significant; annual revision campaigns; and infra-annual revision campaigns. Production processes can be based on workspaces—a data structure specific to JDemetra+ that allows for the use of a graphical interface—or be built entirely in R. <!-- % more precise here GUI vs R world Comm + fluid  -->

Annual campaigns require tools for comparing and prioritizing models in need of manual fine-tuning. The R package JDCruncheR can be used for this purpose. Infra-annual production requires data revision policies and tools for analysis of revisions to validate figures before publication. We detail these three phases by showing the advantages and disadvantages of different configurations, presenting available tools, and comparing execution times. The article includes R code snippets, and a complete example is available in the [{rjd3production} package ](https://tanguybarthelemy.github.io/rjd3production/articles/process.html)

Following a brief overview of the statistical operations comprising the seasonal adjustment process and the JDemetra+ software, the second section outlines the construction of a production chain. The third section covers annual and infra-annual reviews of parameters. The appendices provide a more detailed presentation of the reviewed tools.
